// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestProjectMTech.Api.Data;

#nullable disable

namespace TestProjectMTech.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260621063813_ResetIdentitySequences")]
    partial class ResetIdentitySequences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestProjectMTech.api.Data.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Телевизоры"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Смартфоны"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ноутбуки"
                        });
                });

            modelBuilder.Entity("TestProjectMTech.api.Data.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Телевизор Samsung",
                            Sku = "TV-SAMSUNG-001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Телевизор LG",
                            Sku = "TV-LG-001",
                            Status = "Defective"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Смартфон Xiaomi",
                            Sku = "PHONE-XIAOMI-001",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Смартфон Samsung",
                            Sku = "PHONE-SAMSUNG-001",
                            Status = "WriteOff"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Name = "Ноутбук Lenovo",
                            Sku = "LAPTOP-LENOVO-001",
                            Status = "Defective"
                        });
                });

            modelBuilder.Entity("TestProjectMTech.api.Data.Models.ProductModel", b =>
                {
                    b.HasOne("TestProjectMTech.api.Data.Models.CategoryModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TestProjectMTech.api.Data.Models.CategoryModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
